language: go
go:
- 1.8.x
- 1.10.x
install:
- go get -t github.com/smquartz/go-torznab/...
script:
- go test -v -covermode=count -coverprofile=coverage.out github.com/smquartz/go-torznab/newznab
- "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN"
env:
  global:
    secure: LfOjj/FNHF7vvNG3j3U5TtPpv5kgFhLPfSYc9Va8HldojL5BMsuukJo0X/2Yo/E1S+Hq7nWCRM2v949176xfOttc3CE8Sdfwkie+xvxx4Y2VdhZjs/zvBst6tlLJd5ybAnbxCcH/bph/4o9ds4US8gQVCCTHMBkSxZB9NcHmSwxsY9ObBzDvqZE7zwBZ48rCZZTRkN9qsG7XffEaqD8krVQS+GQ5TjHxwnWrEdIazLZ+/KWpRFNboXnJjzk4dKORghw7PPaWOrI8O3zxg+VLWg4JNzRQOvS+ngDX91w+nbKnu2s6+5buRI3JvaWh+ajhZcbUWMVytMkzZF3TKv/NVVQxgidPwPZuBQMh/1TrN2MPMJXza9Im3aMNUrXUkcbIFabUkgGVAjKKqCGFKuA1MUqQoxDzLgpI0q42X5DfXbxJbEJX6IFXChe0JRraZnh5cuF5IAqBY3QM45QLcpcLNFt+7Gl5CTVGc6Do2QX1+lSBbkaG63U66aHgrmINeM6Kmw5qtrepmzCM53M8TUXc9qMjn7I4pJLQphKP0nU3zMj+FNssl0bNblRy+XANga2q5QZdHHW/fuMEHa3cZ+4YI1lIVGzQG/ftbGKRvM3QqknKfcRkaiNaWnN5dVq0nqFJ4bjOEI3ffhb7gU9Uzmmym3rcB9thQlBxYQEQneO4FYc=
